[GLOBAL]
pants_version = "2.24.2"
backend_packages = [
  "pants.backend.awslambda.python",
  "pants.backend.python"
]

[source]
root_patterns = [
    "/"
]

[python]
interpreter_constraints = [">=3.11,<3.12"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[cli.alias]
lock = "generate-lockfiles --resolve=python-default --diff=true"
