python-interpreter-path = "./dist/export/python/virtualenvs/python-default/3.11.13/bin/python"

search-path = ["."]

project-includes = ["**/*.py"]

project-excludes = [
    "**/__pycache__",
    "**/venv/**",
    "**/.pants.d/**",
    "**/dist/**"
]

disable-search-path-heuristics = false
