python_sources(
    sources=["**/*.py", "!entry_points/**"],
    dependencies=[
        "lambda_common",
        "//:reqs#icoscp"
    ]
)

python_sources(
    name="carbon_monitoring_events",
    sources=["events.py"]
)
