name: CI Pipeline

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pantsbuild/actions/init-pants@v8
        with:
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
      - name: Test with Pants
        run: |
          pants run tests:unittest_runner